# Generated by Django 3.2 on 2022-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtel_data_plan', models.CharField(choices=[('606', '5GB 10,000'), ('605', ' 3GB 10,000'), ('604', '2GB 10,000'), ('603', '1GB 10,000'), ('602', '500MB 10,000')], max_length=20)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MOBILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plan', models.CharField(choices=[('5000', '5GB 10,000'), ('3000', ' 3GB 10,000'), ('2000', '2GB 10,000'), ('1000', '1GB 10,000'), ('500', '500MB 10,000')], max_length=20)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
