# Generated by Django 3.2 on 2022-04-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtn',
            old_name='data_plan',
            new_name='mtn_data_plan',
        ),
    ]
