# Generated by Django 4.0.2 on 2022-03-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_mtn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtn',
            name='volume_field',
            field=models.CharField(choices=[('1', '5GB 10,000'), ('2', ' 3GB 10,000'), ('3', '2GB 10,000'), ('4', '1GB 10,000'), ('5', '500MB 10,000')], default=1, max_length=20),
        ),
    ]
